---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - 'secret'
    - 'configMap'
    - 'hostPath'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
