---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: promtail
  labels:
    app: promtail
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [promtail]
